### ISSUE TITLE
License of logos

### ISSUE THREAD

**Issue by AbdealiLoKo** [dmlc/dmlc.github.io#32]
I wanted to understand what the License/Copyright for the logos in this repo are ?
Is it CC0 ?

I was specifically interested in understanding the license of the xgboost logo: https://github.com/dmlc/dmlc.github.io/blob/master/img/logo-m/xgboost.png

**Comment by tqchen** [comment]
I think it is CC0. feel free to use the logo

**Comment by tqchen** [comment]
cc @mli for confirmation

**Comment by mli** [comment]
confirmed.
